booking/urls.py
from . import views
from django.urls import path


urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('about_us/', views.AboutUs.as_view(), name='about_us'),
    path('menu/', views.Menu.as_view(), name='menu'),


    # BOOKING
    path('bookings/', views.add_booking, name='bookings'),
    path('my_bookings/', views.ShowMyBookings.as_view(), name='my_bookings'),
    path('delete_a_booking/', views.DeleteBooking.as_view(), name='delete_a_booking'),
    path('delete_booking/<booking_id>', views.delete_booking, name='delete_booking'),
    path('edit_booking/<booking_id>', views.edit_booking, name='edit_booking'),
]

mones/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('booking.urls'), name='booking-urls'),
    path('accounts/', include('allauth.urls')),
]

booking/models.py
from django.db import models
import uuid
from django.contrib.auth.models import User
import datetime as dt


class Table(models.Model):
    table_number = models.IntegerField()
    max_no_guests = models.IntegerField()

    def __str__(self):
        return f'Table {self.table_number}, max guests {self.max_no_guests}'


class Booking(models.Model):
    booking_id = models.UUIDField(
        primary_key=True, default=uuid.uuid4, editable=False)
    booked_by = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="user_bookings")
    date = models.DateField(null=False)
    time = models.TimeField(default=dt.time(00, 00))
    no_of_guests = models.IntegerField()
    table = models.ForeignKey(
        Table, on_delete=models.CASCADE, related_name="table", null=True)
    message = models.TextField(blank=True)

    class Meta:
        ordering = ['date']

    def __str__(self):
        return f'Booking {self.date}, {self.time} by {self.booked_by}'

    def assign_table(self):
        """
        Retrives available tables for the bookings date and time,
        excludes the tables that have a booking on the same date
        and time as the requested booking, and orders the tables
        based on the maximum number of guests in ascending order.
        Then returns true if there is a table available.
        """
        if self.date and self.time:
            available_tables = Table.objects.filter(
                max_no_guests__gte=self.no_of_guests
            ).exclude(
                table__date=self.date,
                table__time=self.time
            ).order_by('max_no_guests')

            if available_tables:
                self.table = available_tables.first()
                self.save()
                return True
        self.table = None
        return False

    def save(self, *args, **kwargs):
        if not self.pk:
            # If its a new booking, assign a table
            self.assign_table()
        super().save(*args, **kwargs)

booking/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import Booking
import datetime as dt

BOOKING_TIMES = [(
    dt.time(hour=x), '{:02d}:00'.format(x)) for x in range(16, 22)]

NO_OF_GUESTS_CHOICE = [
    (1, "1"),
    (2, "2"),
    (3, "3"),
    (4, "4"),
    (5, "5"),
    (6, "6"),
]


class BookingForm(forms.ModelForm):
    """Booking Form"""

    class Meta:
        model = Booking
        fields = ['date', 'time', 'no_of_guests', 'message']
        widgets = {'time': forms.Select(
            choices=BOOKING_TIMES), 'no_of_guests': forms.Select(
                choices=NO_OF_GUESTS_CHOICE), 'date': forms.DateInput(
                attrs={'type': 'date', 'placeholder': 'yyyy-mm-dd (DOB)'}),
                'message': forms.Textarea(attrs={
                    'placeholder': 'Write your message here..'})}

booking/views.py
from django.shortcuts import render, reverse, redirect, get_object_or_404
from django.views import generic, View
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .models import Booking, Table
from .forms import BookingForm


class Home(generic.TemplateView):
    """Open landing page"""
    template_name = "index.html"


class AboutUs(generic.TemplateView):
    """Open About us page"""
    template_name = "about_us.html"


class Menu(generic.TemplateView):
    """Open Menu page"""
    template_name = "menu.html"


class DeleteBooking(generic.TemplateView):
    """Open Delete a booking page"""
    template_name = "delete_a_booking.html"


class ShowMyBookings(generic.ListView):
    """Show the users bookings"""
    model = Booking
    template_name = 'my_bookings.html'

    def get_queryset(self):
        return Booking.objects.filter(booked_by=self.request.user)


@login_required()
def add_booking(request):
    """
    Allows a user to make a booking, and checks
    if a table is available for the amount of guests,
    and requested day and time. Also prevent users
    from making more than one booking on the same day.
    """

    if request.method == 'POST':
        form = BookingForm(request.POST)
        if form.is_valid():
            booking_date = form.cleaned_data['date']
            booking_time = form.cleaned_data['time']

            booking = form.save(commit=False)
            booking.booked_by = request.user

            # Check if any available tables
            if booking.assign_table():
                booking.save()
                messages.success(request, 'Booking completed')
                return redirect(reverse('my_bookings'))

            else:
                messages.error(
                    request,
                    'No more available tables for this day and time.'
                )
        else:
            messages.error(
                request, 'An error occurred, please try again')
    else:
        form = BookingForm()

    template = 'bookings.html'
    context = {
        'form': form
    }

    return render(request, template, context)


@login_required()
def delete_booking(request, booking_id):
    """
    Users can choose to delete a booking. The delete booking
    page give the users information that this cant be undone,
    and if they chose cancel they will be redirected back to my bookings.
    If they click on the delete button the booking will be
    deleted permanently.
    """
    booking = get_object_or_404(Booking, booking_id=booking_id)

    if request.method == "POST":
        booking.delete()
        messages.success(request, 'Your booking has been deleted!')
        return redirect(reverse('my_bookings'))

    template = 'delete_a_booking.html'
    context = {
        'booking': booking,
    }

    return render(request, template, context)


@login_required()
def edit_booking(request, booking_id):
    """
    Users can edit their bookings time, date,
    and number of persons. Initializes the form
    with the form data and the existing booking instance,
    checks if the form is valid and if so save it.

    """
    booking = get_object_or_404(Booking, booking_id=booking_id)

    if request.method == 'POST':
        form = BookingForm(request.POST, instance=booking)
        if form.is_valid():
            booking = form.save(commit=False)

            if booking.assign_table():
                booking.save()
                messages.success(request, 'Your booking has been updated')
                return redirect('my_bookings')
            else:
                messages.error(
                    request, 'No more available tables for this day and time.')
    else:
        form = BookingForm(instance=booking)

    template = 'edit_booking.html'
    context = {
        'form': form,
    }

    return render(request, template, context)

templates/about_us.html
{% extends "base.html" %}

{% block content %}

<h3 class="text-center">Welcome to us!</h3>
<br>
<div class="text-center">
    <p>We are a small restaurant located by the port of Helsingborg. </p>
    <p>Our menu is based on the Swedish cousine with only locally produced ingredients.</p>
    <p>We put our heart and soul into our food and we know you will feel that in the taste.</p>
    <br>
    <p>Check out our menu, you wont be disapointed!</p>
    <p>If you have any question, send us an email or give us a call.</p>
    <p>Hope to see you here soon!</p>
    <p>Best Regards</p>
    <p>Mönes Team</p>
</div>
{%endblock%}

templates/base.html
{% load static %}
{% load cloudinary %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0 shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="Description" content="Mönes Restaurant">
    <meta name="keywords" content="restaurant, swedish, swedish food, south of sweden, helsingborg">

    <!-- Favicon-->
    <link rel="icon" type="image/png"
        href="https://res.cloudinary.com/dq785n55j/image/upload/v1684740357/favicon_jugjua.png">

    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css"
        integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">

    <!-- CSS -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <title>Mönes | Restaurant</title>
</head>

<body>

    <!-- Header -->
    <header>
        <hr class="page-break">
        
        <!-- Navigation -->
        <nav class="navbar navbar-expand-lg navbar-light">
            <div class="container">
                <a class="navbar-brand" href="{% url 'home' %}">
                    <img src="https://res.cloudinary.com/dq785n55j/image/upload/v1684756312/logo_transparent_knaope.png"
                        width="300" height="300" class="d-inline-block align-top" alt="restaurant-logo">
                </a>
                <p></p>

                <!-- Hamburger dropdown menu -->
                <button class="navbar-toggler navbar-light ml-auto" type="button" data-toggle="collapse"
                    data-target="#navbarContent" aria-controls="navbarContent" aria-expanded="false"
                    aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse justify-content-end" id="navbarContent">
                    <ul class="navbar-nav mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link" aria-current="page" href="{% url 'home' %}">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" aria-current="page" href="{% url 'about_us' %}">About Us</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" aria-current="page" href="{% url 'menu' %}">Menu</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" aria-current="page" href="{% url 'bookings' %}">Book</a>
                        </li>
                        {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'my_bookings' %}">My bookings</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'account_logout' %}">Logout</a>
                        </li>
                        {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'account_signup' %}">Sign Up</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'account_login' %}">Login</a>
                        </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Navigation End -->
        <hr class="page-break">
    </header>
    <!-- Header End -->

    <!-- Messages (Code used from Code Institute Blog Walkthrough) -->
    <div class="container">
        <div class="row">
            <div class="col-md-8 offset-md-2">
                {% for message in messages %}
                <div class="alert {{ message.tags }} alert-dismissible fade show" id="msg" role="alert">
                    {{ message | safe }}
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
    <!-- Messages End -->

    <div>
        {% block content %}
        <!-- Content Goes here -->
        {% endblock content %}
    </div>

    <!-- Footer Start -->
    <footer id="footer">
        <div class="container footer-content">
            <div class="row">
                <div class="col-footer col-lg-4 col-md-6">
                    <div class="footer-info">
                        <h3>Mönes Restaurant</h3>
                        <p>Prisma, OceanHamnen</p>
                        <p>Helsingborg</p>
                    </div>
                </div>
                <div class="col-footer col-lg-4 col-md-6">
                    <div class="footer-contact">
                        <h3>Contact</h3>
                        <p>Phone: +46 123 45 678</p>
                        <p>Email: info@monesrestaurant.se</p>
                    </div>
                </div>
                <div class="col-footer col-lg-4 col-md-6">
                    <div class="footer-book">
                        <h3>Book Now</h3>
                        <ul>
                            <li>
                                <a class="nav-link" aria-current="page" href="{% url 'home' %}">Home</a>
                            </li>
                            <li>
                                <a class="nav-link" aria-current="page" href="{% url 'bookings' %}">Booking</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!-- Footer End -->

    <!-- Message Fade (Code used from Code Institute Blog Walkthrough)  -->
    <script>
        setTimeout(function () {
            let messages = document.getElementById("msg");
            let alert = new bootstrap.Alert(messages);
            alert.close();
        }, 3000);
    </script>
    <!-- Message Fade End -->

    <!-- Font awesome script-->
    <script src="https://kit.fontawesome.com/942f7e0d1a.js" crossorigin="anonymous"></script>

    <!-- Bootstrap scripts -->
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous">
    </script>
</body>

</html>

templates/bookings.html
{% extends "base.html" %}



{% block content %}


<section class="container text-center p-2">
    <h2>Book Your Table</h2>
    <br>

    {% if user.is_authenticated %}
    <div class="row justify-content-center">
        <div class="col-12 col-md-9 col-lg-6 mb-3">

            <p>If you are a group bigger than 6 persons, please contact us for booking. </p>

            <form class="form" method="POST" action="{% url 'bookings' %}">
                {% csrf_token %}
                {{ form.as_p }}
                <input class="btn" type="submit" value="Book Now">
            </form>
            {% else %}
            <p>To make a booking please <a href="{% url 'account_signup' %}"><strong>Sign up</strong></a> or<a
                    href="{% url 'account_login' %}">
                    <strong>Log in</strong></a> to your account.</p>
            {% endif %}
        </div>
    </div>
</section>

{% endblock %}

templates/delete_a_booking.html
{% extends "base.html" %}

{% block content %}

<div class="container text-center mb-2">
    <h2>Delete Booking</h2>
    <div class="row justify-content-center">
        <br>
        <div class="card form">
            <div class="card-body">

                <br>
                <p>You are about to delete your booking for:</p>
                <p>{{ booking.date }}</p>
                <p>Time: {{ booking.time }}</p>
                <br>
                <p>Do you wish to continue?</p>
                <p class="text-decoration-underline"><strong>This action cannot be undone.</strong></p>
                <form action="{% url 'delete_booking' booking.booking_id %}" method="POST">
                    {% csrf_token %}
                    <div class="text-center mt-3">
                        <a href="{% url 'my_bookings' %}" class="btn cancel-submit mt-3">Cancel</a>
                        <button class="btn submit mt-3">Delete Booking</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

{%endblock%}

templates/edit_booking.html
{% extends "base.html" %}

{% block content %}

<section class="container">
    <h2>Edit Booking</h2>
    <br>
    <p>If you are a group bigger than 6 persons, please contact us for booking. </p>

    <form method="POST">

        {% csrf_token %}
        {{ form.as_p }}
        <input class="btn" type="submit" value="Edit Booking">
        <a href="{% url 'my_bookings' %}" class="btn cancel-submit">Cancel</a>

    </form>
</section>

{%endblock%}

templates/index.html
{% extends "base.html" %}

{% block content %}

    <div class="hero-content container-fluid">

        <div class="hero-image z-1">
            <img src="https://res.cloudinary.com/dq785n55j/image/upload/v1684864863/kottbulle_lx604v.png"
                class="img-fluid" alt="picture-of-meatballs">
            <div class="opaque-overlay"></div>
        </div>
    </div>

{%endblock%}

templates/menu.html
{% extends "base.html" %}

{% block content %}

<div class="container">
    <h1 class="text-center">Menu</h1>
    <br>
    <div class="row">
        <div class="col-lg-4 col-md-6">
            <h2>Starters</h2>
            <hr class="column-break">
            <div class="menu-item">
                <h4>TOAST SKAGEN</h4>
                <p>shrimp, mayonnaise, vendace roe, butter-fried toast</p>
                <p class="price">Price .............. 210/295 SEK</p>
            </div>
            <br>
            <div class="menu-item">
                <h4>STEAK TARTARE</h4>
                <p>Classic Swedish Beef Tartare; beets, capers, red onion, chives,
                    raw egg yolk & Dijon mustard</p>
                <p class="price">Price .............. 210 SEK</p>
            </div>
            <br>
            <div class="menu-item">
                <h4>GOAT CHEESE SALAD</h4>
                <p>Goat cheese salad with roasted beetroots and walnuts</p>
                <p class="price">Price .............. 180 SEK</p>
            </div>
            <br>
            <div class="menu-item">
                <h4>TOAST PELLE JANZON</h4>
                <p>filet of beef on toast, vendace roe, red onion & egg yolk</p>
                <p class="price">Price .............. 225 SEK</p>
            </div>
            <br>
        </div>

        <div class="col-lg-4 col-md-6">
            <h2>Mains</h2>
            <hr class="column-break">
            <div class="menu-item">
                <div class="menu-item">
                    <h4>OUR FAMOUS MEATBALLS</h4>
                    <p>meatballs in cream sauce, lingonberries, pickled cucumber,
                        potato puree</p>
                    <p class="price">Price .............. 220 SEK</p>
                </div>
                <br>
                <h4>TOMATO PIE</h4>
                <p>served with salad, roasted salad topping & Strawberry Vinegar</p>
                <p class="price">Price .............. 180 SEK</p>
            </div>
            <br>
            <div class="menu-item">
                <h4>BIFF RYDBERG</h4>
                <p>classic minced veal pattie, lingonberries, petit pois, potatoe
                    puree</p>
                <p class="price">Price .............. 249 SEK</p>
            </div>
            <br>
            <div class="menu-item">
                <h4>WALLENBERGARE</h4>
                <p>classic minced veal pattie, lingonberries, petit pois, potatoe puree</p>
                <p class="price">Price .............. 255 SEK</p>
            </div>
            <br>
            <div class="menu-item">
                <h4>LINGUINI PASTA WITH SPRING ONIONS</h4>
                <p>served with pesto made of spring onions from Skåne , artichokes,
                    semi-dried tomatoes & salt-roasted almonds.</p>
                <p class="price">Price .............. 160 SEK</p>
            </div>
            <br>
            <div class="menu-item">
                <h4>BUTTER FRIED PERCH</h4>
                <p>fried perch, sandefjors sauce, almond potatoe stomp, baked
                    leek, smoked salmon emulsion & pickled turnip</p>
                <p class="price">Price .............. 239 SEK</p>
            </div>
            <br>
            <div class="menu-item">
                <h4>SALMON WITH DILL STEWED POTATOES</h4>
                <p>Lightly cured salmon with dill stewed potatoes</p>
                <p class="price">Price .............. 219 SEK</p>
            </div>
            <br>
        </div>

        <div class="col-lg-4 col-md-6">
            <h2>Desserts</h2>
            <hr class="column-break">
            <div class="menu-item">
                <h4>RHUBARB PIE</h4>
                <p>baked with almond pulp and brown sugar & served with homemade custard</p>
                <p class="price">Price .............. 85 SEK</p>
            </div>
            <br>
            <div class="menu-item">
                <h4>MERINGUE SWISS</h4>
                <p>Meringue swiss, elderberry ice cream, strawberry cream, strawberry sauce</p>
                <p class="price">Price .............. 95 SEK</p>
            </div>
            <br>
            <div class="menu-item">
                <h4>SWEDISH CHOCOLATE BALL</h4>
                <p>An absolutely delicious chocolate ball with roasted coconut</p>
                <p class="price">Price .............. 35 SEK</p>
            </div>
            <br>
            <div class="menu-item">
                <h4>FRENCH TOAST "FATTIGA RIDDARE"</h4>
                <p>with apple compote, oat crumble, cardamom ice cream, cinnamon and almond crackers</p>
                <p class="price">Price .............. 95 SEK</p>
            </div>
            <br>
            <div class="menu-item">
                <h4>LEMON CAKE</h4>
                <p>with rhubarb sorbet, lemon curd, dried blueberries, baked white chocolate and lemon meringue</p>
                <p class="price">Price .............. 98 SEK</p>
            </div>
        </div>
    </div>
</div>

{%endblock%}

templates/my_bookings.html
{% extends "base.html" %}

{% block content %}

<div class="container">
  <h2 class="text-center">My Bookings</h2>
  <br>
  <div class="row">
    {% for booking in booking_list %}
    <div class="col-md-4">
      <div class="card mb-4">
        <div class="card-body">
          <h5 class="card-title">Booking:</h5>
          <p class="card-text">Date: {{ booking.date }}</p>
          <p class="card-text">Time: {{ booking.time }}</p>
          <p class="card-text">Persons: {{ booking.no_of_guests }}</p>
          <a href="{% url 'edit_booking' booking.booking_id %}" class="btn btn-my-bookings">Edit Booking</a>
          <a href="{% url 'delete_booking' booking.booking_id %}" class="btn btn-my-bookings">Delete Booking</a>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>

  {%endblock%}